### ISSUE TITLE
WPILib GradleRIO vendordeps json file out of date

### ISSUE THREAD

**Issue by GreenPiggies** [REVrobotics/Color-Sensor-v3#6]
We would like to use `ColorSensorResolution` and `ProximitySensorMeasurementRate` enums in our code but they are not public in the current release.

Can the WPILib GradleRIO vendordeps JSON file (http://www.revrobotics.com/content/sw/color-sensor-v3/sdk/REVColorSensorV3.json) be updated with the latest code so we can access these enums?

**Comment by willtoth** [comment]
Working on packaging the actual release. This will be available soon.
